default:
    image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1

stages:
 - test
 
test:
 stage: test
 script: 
  - npm install
  - npx cypress run testsonChrome


